<a href="https://colab.research.google.com/github/pko89403/DeepLearningSelfStudy/blob/master/Conv1D_Layer_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch
from torch import nn

Conv1D 입력 채널 1, 출력 채널 1

In [0]:
input_data = torch.randn(1, 1, 1)
conv_1D = nn.Conv1d(in_channels=1,
                    out_channels=1,
                    kernel_size=1,
                    stride=1)
print(conv_1D, conv_1D.weight, conv_1D.bias)

Conv1d(1, 1, kernel_size=(1,), stride=(1,)) Parameter containing:
tensor([[[0.0983]]], requires_grad=True) Parameter containing:
tensor([0.3718], requires_grad=True)


Conv1D 입력 채널 3, 출력 채널 2

In [0]:
conv_1D = nn.Conv1d(in_channels=3,
                    out_channels=2,
                    kernel_size=1,
                    stride=1)
print(conv_1D, conv_1D.weight, conv_1D.bias)

Conv1d(3, 2, kernel_size=(1,), stride=(1,)) Parameter containing:
tensor([[[-0.5065],
         [ 0.3666],
         [-0.4514]],

        [[-0.4296],
         [-0.3291],
         [-0.3929]]], requires_grad=True) Parameter containing:
tensor([ 0.4929, -0.3040], requires_grad=True)


Conv1D 입력 채널 2, 출력 채널 3

In [0]:
conv_1D = nn.Conv1d(in_channels=2,
                    out_channels=3,
                    kernel_size=1,
                    stride=1)
print(conv_1D, conv_1D.weight, conv_1D.bias)

Conv1d(2, 3, kernel_size=(1,), stride=(1,)) Parameter containing:
tensor([[[-0.4058],
         [-0.3017]],

        [[ 0.6924],
         [ 0.0805]],

        [[ 0.0910],
         [-0.0240]]], requires_grad=True) Parameter containing:
tensor([-0.6016, -0.1853,  0.5337], requires_grad=True)


Conv1D 입력 채널 1, 출력 채널 1, 커널 크기 1, 스트라이드 1일때 계산해보기

In [0]:
input_data = torch.randn(1, 1, 1)
conv_1D = nn.Conv1d(in_channels=1,
                    out_channels=1,
                    kernel_size=1,
                    stride=1)
print(conv_1D, conv_1D.weight, conv_1D.bias)
out = conv_1D(input_data)
print(f"Conv1D 출력 값은 : {out}")

Conv1d(1, 1, kernel_size=(1,), stride=(1,)) Parameter containing:
tensor([[[0.9593]]], requires_grad=True) Parameter containing:
tensor([-0.0365], requires_grad=True)
Conv1D 출력 값은 : tensor([[[0.3853]]], grad_fn=<SqueezeBackward1>)


In [0]:
input_data_val = input_data
conv_1d_w = conv_1D.weight.data
conv_1d_b = conv_1D.bias.data
print(f"입력 데이터 : {input_data_val},\t Conv1D의 Weight : {conv_1d_w},\t Conv1D의 가중치 : {conv_1d_b}")

입력 데이터 : tensor([[[0.4397]]]),	 Conv1D의 Weight : tensor([[[0.9593]]]),	 Conv1D의 가중치 : tensor([-0.0365])


In [0]:
y = conv_1d_w * input_data + conv_1d_b # y = weight x + bias
print(f"Conv1D 재현 값 : {y}")

Conv1D 재현 값 : tensor([[[0.3853]]])


Conv1D 입력 채널 1, 출력 채널 1, 커널 크기 2, 스트라이드 1일때 계산해보기

In [0]:
input_data = torch.randn(1, 1, 3)
conv_1D = nn.Conv1d(in_channels=1,
                    out_channels=1,
                    kernel_size=2,
                    stride=1)

out = conv_1D(input_data) 
print(out.size())
print(conv_1D, conv_1D.weight)

torch.Size([1, 1, 2])
Conv1d(1, 1, kernel_size=(2,), stride=(1,)) Parameter containing:
tensor([[[ 0.4348, -0.2589]]], requires_grad=True)


In [0]:
input_tensor2data = input_data.numpy()[0,0,]
conv1d_weight = conv_1D.weight.data.numpy()[0,0,]
conv1d_bias = conv_1D.bias.data.numpy()

In [0]:
print(f"입력 데이터 : {input_tensor2data},\t Conv1D의 Weight : {conv1d_weight},\t Conv1D의 가중치 : {conv1d_bias}")

입력 데이터 : [ 0.9162371 -1.3271387  0.5480737],	 Conv1D의 Weight : [ 0.43479627 -0.25887537],	 Conv1D의 가중치 : [0.09194225]


In [0]:
print(f"Conv1D 출력 값은 : {out}")

Conv1D 출력 값은 : tensor([[[ 0.8339, -0.6270]]], grad_fn=<SqueezeBackward1>)


In [0]:
output = list()
for data_index, data in enumerate(input_tensor2data):
  
  temp = 0
  for conv_idx, conv_w in enumerate(conv1d_weight):
    if(data_index + conv_idx == len(input_tensor2data)): 
      temp = 0
      break
    temp += ( input_tensor2data[data_index+conv_idx] * conv_w )

  if(temp != 0 ):
    output.append(temp)

print(f"Conv1D 재현 값 : {output + conv1d_bias}")

Conv1D 재현 값 : [ 0.83388227 -0.62697548]


Conv1D 입력 채널 1, 출력 채널 1,  커널 크기 2, 스트라이드 2일때 계산해보기

In [0]:
input_data = torch.randn(1, 1, 4)
conv_1D = nn.Conv1d(in_channels=1,
                    out_channels=1,
                    kernel_size=2,
                    stride=2)

out = conv_1D(input_data) 
print(out.size())
print(conv_1D, conv_1D.weight)

input_tensor2data = input_data.numpy()[0,0,]
conv1d_weight = conv_1D.weight.data.numpy()[0,0,]
conv1d_bias = conv_1D.bias.data.numpy()

print(f"입력 데이터 : {input_tensor2data},\t Conv1D의 Weight : {conv1d_weight},\t Conv1D의 가중치 : {conv1d_bias}\n")
print(f"Conv1D 출력 값은 : {out}")

torch.Size([1, 1, 2])
Conv1d(1, 1, kernel_size=(2,), stride=(2,)) Parameter containing:
tensor([[[ 0.3871, -0.6080]]], requires_grad=True)
입력 데이터 : [-1.3365821  -0.79337174  0.30488676 -0.2093321 ],	 Conv1D의 Weight : [ 0.38709778 -0.608002  ],	 Conv1D의 가중치 : [0.42661768]

Conv1D 출력 값은 : tensor([[[0.3916, 0.6719]]], grad_fn=<SqueezeBackward1>)


In [0]:
output = list()
stride = 2
for data_index, data in enumerate(input_tensor2data):
  
  if(data_index % stride != 0): continue # stride 처리 해주는 부분
  
  temp = 0
  for conv_idx, conv_w in enumerate(conv1d_weight):
    if(data_index + conv_idx == len(input_tensor2data)): 
      temp = 0
      break
    temp += ( input_tensor2data[data_index+conv_idx] * conv_w )

  if(temp != 0 ):
    output.append(temp)

print(f"Conv1D 재현 값 : {output + conv1d_bias}")

Conv1D 재현 값 : [0.39160135 0.67191301]
