[참고](https://www.aiworkbox.com/lessons/calculate-the-element-wise-hadamard-multiplication-of-matrices-in-pytorch)

In [1]:
import torch 
torch.__version__

'1.6.0'

In [4]:
random_tensor_one_ex = (torch.rand(2, 3, 4) * 10).int()
random_tensor_one_ex

tensor([[[1, 5, 9, 7],
         [4, 9, 5, 1],
         [9, 3, 8, 0]],

        [[0, 7, 6, 6],
         [0, 5, 5, 1],
         [2, 1, 1, 8]]], dtype=torch.int32)

In [9]:
random_tensor_two_ex = (torch.rand(2, 3, 4) * 10).int()
random_tensor_two_ex

tensor([[[2, 6, 9, 5],
         [1, 3, 7, 8],
         [9, 6, 4, 8]],

        [[5, 1, 6, 6],
         [9, 5, 7, 7],
         [1, 7, 8, 4]]], dtype=torch.int32)

In [6]:
hadamard_product_ex = random_tensor_one_ex * random_tensor_two_ex
hadamard_product_ex

tensor([[[ 2, 20, 45,  0],
         [16, 18,  0,  4],
         [72,  9,  8,  0]],

        [[ 0, 14, 36, 36],
         [ 0, 25, 30,  5],
         [10,  0,  4, 72]]], dtype=torch.int32)

In [ ]:
s