<a href="https://colab.research.google.com/github/pko89403/DeepLearningSelfStudy/blob/master/Softmax_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1) # 동일한 결과를 원하지않니?

In [2]:
z = torch.FloatTensor([1, 2, 3])

hypothesis = F.softmax(z, dim=0)
print(hypothesis)

print(hypothesis.sum())

tensor([0.0900, 0.2447, 0.6652])
tensor(1.)


Cross Entropy Loss ( low )
- class = 6
- sample = 3

In [6]:
z = torch.rand(3, 5, requires_grad=True)
hypothesis = F.softmax(z, dim=1) # dim=1을 없애서 softmax하라
print(hypothesis) # 예측 결과 y^hat

tensor([[0.1405, 0.1378, 0.1741, 0.3437, 0.2039],
        [0.2089, 0.1337, 0.2755, 0.1365, 0.2454],
        [0.2015, 0.1539, 0.2590, 0.1536, 0.2320]], grad_fn=<SoftmaxBackward>)


In [9]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([1, 3, 1])


In [10]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0.]])

In [11]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean() # (3,5) x (3, 5) -> (3, 1) -> scalar
print(cost)

tensor(1.9484, grad_fn=<MeanBackward0>)


In [12]:
F.nll_loss(F.log_softmax(z, dim=1), y) # High level Negative Log Likelihood

tensor(1.9484, grad_fn=<NllLossBackward>)

In [0]:
F.cross_entropy(z, y) # nll_loss + log_softmax