<a href="https://colab.research.google.com/github/pko89403/DeepLearningSelfStudy/blob/master/TensorManipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Vector, Matrix and Tensor
차원이 없는 값들을 scala   
차원이 있는 값 중 1차원 vector, 2차원 matrix(행렬), 3차원 tensor

### Pytorch Tensor Shape Convention
- 2D Tensor
  - 가장 기본적인 크기 
  - |t| = (batch size, dim ) : batch size * dim 

- 3D Tensor 
  - 비전에서 가장 일반적인
    - |t| = (batch size, width, height ) 
  - 자연어 처리에서
    - |t| = (batch size, length, dim )

In [0]:
import numpy as np
import torch

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  1
Shape of t :  (7,)


In [4]:
print('t[0] t[1] t[-1]  = ', t[0], t[1], t[-1]) # elemnent
print('t[2:5] t[4:-1] = ', t[2:5], t[4:-1]) # slicing
print('t[:2] t[3:]  = ', t[:2], t[3:])

t[0] t[1] t[-1]  =  0.0 1.0 6.0
t[2:5] t[4:-1] =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]  =  [0. 1.] [3. 4. 5. 6.]


In [6]:
# 2차원 배열
t = np.array([[0., 1., 2.], 
              [3., 4., 5.],
              [6., 7., 8.]])
print('Rank of t : ', t.ndim)
print('Shape of t : ', t.shape)

Rank of t :  2
Shape of t :  (3, 3)


In [7]:
# 파이토치에 대해서 똑같이
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [9]:
print('Rank : ', t.dim())
print('Shape : ', t.shape)
print('Size : ', t.size())
print('Element : ', t[0], t[1], t[-1])
print('Slicing : ', t[2:5], t[4:-1])
print('Slicing : ', t[:2], t[3:])

Rank :  1
Shape :  torch.Size([7])
Size :  torch.Size([7])
Element :  tensor(0.) tensor(1.) tensor(6.)
Slicing :  tensor([2., 3., 4.]) tensor([4., 5.])
Slicing :  tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [10]:
t = torch.FloatTensor([[1., 2., 3.,],
                       [4., 5., 6.,],
                       [7., 8., 9.,],
                       [10., 11., 12.]
                       ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [11]:
print('Rank : ', t.dim())
print('Shape : ', t.shape)
print('Size : ', t.size())
print('Element : ', t[:, 1])
print('Slicing size : ', t[:, 1].size())
print('Slicing : ', t[:, :-1])

Rank :  2
Shape :  torch.Size([4, 3])
Size :  torch.Size([4, 3])
Element :  tensor([ 2.,  5.,  8., 11.])
Slicing size :  torch.Size([4])
Slicing :  tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


### BroadCasting
파이토치는 BroadCasting을 지원한다.  
다른 shape의 tensor들의 사이즈를 자동으로 맞추어 연산을 진행하는 것   
자동으로 진행되므로 조금 신경 쓸 필요가 있다

In [12]:
 # same shape
 m1 = torch.FloatTensor([[3, 3]])
 m2 = torch.FloatTensor([[2, 2]])
 print(m1 + m2 )

tensor([[5., 5.]])


In [13]:
# vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])
print(m1 + m2)

tensor([[4., 5.]])


In [14]:
# 2 x 1 Vector + 1 x 2 Vector
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2) # [3] * 2 , [4]* 2

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication

In [15]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])

print('Shape of Matrix 1: ', m1.shape)
print('Shape of Matrix 2: ', m2.shape)
print(m1.matmul(m2))

Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])


In [17]:
print(m1 * m2 ) # element wise 곱이 된다. [1,2,3,4] x [1,1,2,2]
print(m1.mul(m2)) # 계산 결과 [1*1, 1*2, 3*2, 4*2]

tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean ( 특정 dimension을 없애주라 )
Sum, Max 도 dim에 대해 같은 방식이다.

In [18]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [19]:
t = torch.FloatTensor([[1,2],[3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [21]:
print( t.mean() )
print( t.mean(dim=0) ) # 0번째 차원을 없애 주라 -> [ (1+3) / 2, (2+4) / 2 ]
print( t.mean(dim=1) ) # 1번째 차원을 없애 주라 ^  [ (1+2) / 2, (3+4) / 2 ]
print( t.mean(dim=-1) )

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


### View( Reshape )
모양을 다시 만들어 준다.   
-1은 잘 모르겠으니깐 알아서 해라는 뜻!

In [25]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
               [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [26]:
print(ft.view([-1,3])) # 앞에껀 모르겠고 3개씩 가지는 걸로 만들어줘
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [27]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze( 쥐어 짠다라는 뜻 )
자동으로 element가 1인 차원 하나를 없애준다.
### Unsqueeze ( 반대로 )
내가 원하는 차원에 element 하나를 넣어준다. 원하는 차원을 명시해야한다.


In [30]:
ft = torch.FloatTensor([[0], [1], [2]])
print( ft )
print( ft.shape )

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [31]:
print( ft.squeeze() )
print( ft.squeeze().shape )

tensor([0., 1., 2.])
torch.Size([3])


In [32]:
ft = torch.Tensor([0,1,2])
print(ft.shape)

torch.Size([3])


In [34]:
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])
tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [35]:
print(ft.unsqueeze(1))
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Type Casting

In [36]:
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [37]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [38]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [39]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [0]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [41]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


### Stacking

In [47]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])
print(x.shape)

torch.Size([2])


In [45]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim =1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [46]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [48]:
x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [49]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [0]:
x = torch.FloatTensor([[1,2], [3,4]])

In [51]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) # IN-PLACE 모드 
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
