# 파이토치
페이스북의 인공지능 프레임워크, 사용하면 건강해진다.

파이토치에서는 데이터의 기본 단위로 tensor를 사용한다. tensor는 다차원 배열(array) 라고 정의할 수 있다.

## 선형회귀분석
주어진 데이터를 가장 잘 설명하는 직선 하나를 찾는 것.
- 하나의 독립변수 : Simple Linear Regression
- 여러개 독립변수 : Multivariate Linear Regression

torch.tensor 함수는 인수로 data, dtype, device, requires_grad 등을 받는다.
- data : 배열이 들어간다.
- dtype : 데이터를 저장할 자료형이 들어간다.
- device : tensor를 어느 기기에 올릴건지 명시한다.
- requires_grad : 이 tensor에 대한 기울기를 저장할지 여부를 지정한다. ( Default : False )

In [2]:
import torch
X = torch.Tensor(2, 3)
print(X)

tensor([[0.0000e+00, 2.0000e+00, 0.0000e+00],
        [2.0000e+00, 1.1210e-44, 0.0000e+00]])


In [3]:
X = torch.tensor( [[1,2,3], [4,5,6]])
print(X)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [5]:
x_tensor = torch.tensor(data=[2.0, 3.0], requires_grad=True)
print(x_tensor)

tensor([2., 3.], requires_grad=True)


아래의 코드는 z의 식에서 x에 대한 기울기를 구하는 단순한 코드.\
x라는 텐서를 생성하며 기울기를 계산하도록 지정했고, 따라서 z라는 변수에 연산 그래프의 결괏값이 저장됩니다.\
z와 target 절댓값 차이를 계산하고 torch.sum()이란 함수를 통해 두 값의 차이를 숫자 하나로 바꾼다.\
loss.backward() 함수를 호출하면 연산 그래프를 쭉 따라가면서 잎노드(x)에 대한 기울기를 계산합니다.

In [7]:
import torch

x = torch.tensor(data=[2.0, 3.0], requires_grad=True)
y = x**2
z = 2*y + 3

target = torch.tensor([3.0, 4.0])
loss = torch.sum(torch.abs( z - target ))
loss.backward()

print(x.grad, y.grad, z.grad)

None
tensor([ 8., 12.]) None None


x 라는 변수에 [num_data, 1] 모양의 텐서를 생성하는데 이 tensor의 값을 -10 부터 10 까지 균등하게 초기화\
y 에 노이즈를 추가하기 위해 y_noise 라는 변수 정규분포를 따르는 변수를 초기화한다\
Linear 클래스는 들어오는 feature의 수, 결과로 나오는 feature의 수, bias 사용 여부를 초기화 인수로 받아서 생성\
최적화 할 변수로 model.prameters()라는 함수를 사용하여 선형회귀 모델의 변수 w와 b를 전달헀고 lr을 전달했다\
각 반복시 지난번에 계산했던 기울기를 0으로 초기화하는 optimizer.zero_grad()를 실행한다\
기울기를 초기화해야 새로운 가중치와 편차에 대해 새로운 기울기를 구할 수 있기 떄문이다\
loss에 output과 y_noise의 차이를 저장하고 loss.backward() 함수를 호출하면 각 변수 w, b에 대한 기울기가 계산된다\
optmizer의 step 함수를 통해 인수로 들어갔던 model.parameters()에서 리턴되는 변수들의 기울기에 학습율 0.01을 곱하여 빼줌으로써 업데이트한다\


In [9]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.init as init

num_data = 1000
num_epoch = 500

x = init.uniform_(torch.Tensor(num_data, 1), -10, 10)
noise = init.normal_(torch.FloatTensor(num_data, 1), std=1)
y = 2*x + 3
y_noise = 2 * (x + noise) + 3

model = nn.Linear(1, 1)
loss_func = nn.L1Loss()

optimizer = optim.SGD(model.parameters(), lr=0.01)

label = y_noise
for i in range(num_epoch):
    optimizer.zero_grad()
    output = model(x)
    
    loss = loss_func(output, label)
    loss.backward()
    optimizer.step()
    
    if i % 10 == 0:
        print(loss.data)
        param_list = list(model.parameters())
        print(param_list[0].item(), param_list[1].item())

tensor(8.4425)
0.4011380672454834 0.9391444325447083
tensor(6.1787)
0.8753024339675903 0.9556044340133667
tensor(4.1668)
1.319082498550415 0.9800844788551331
tensor(2.8963)
1.6609995365142822 1.0201045274734497
tensor(2.4223)
1.8570470809936523 1.074844479560852
tensor(2.3059)
1.9358597993850708 1.13418447971344
tensor(2.2605)
1.9668447971343994 1.193204641342163
tensor(2.2237)
1.9844006299972534 1.2506046295166016
tensor(2.1918)
1.9906543493270874 1.3064446449279785
tensor(2.1625)
1.9930152893066406 1.3604249954223633
tensor(2.1343)
1.992275595664978 1.4134451150894165
tensor(2.1072)
1.9896851778030396 1.4653050899505615
tensor(2.0823)
1.988305926322937 1.5150450468063354
tensor(2.0587)
1.9865025281906128 1.5635448694229126
tensor(2.0363)
1.988284707069397 1.6106847524642944
tensor(2.0152)
1.990668535232544 1.6563447713851929
tensor(1.9957)
1.9915516376495361 1.7005046606063843
tensor(1.9767)
1.994051218032837 1.743884801864624
tensor(1.9592)
1.9960625171661377 1.785544753074646
tenso